# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: \.md$
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0  # Use the ref you want to point at
  hooks:
  - id: trailing-whitespace
    name: trim trailing whitespaces
    description: trims trailing whitespace.
    entry: trailing-whitespace-fixer
    language: python
    types: [text]
    stages: [pre-commit, pre-push, manual]

  - id: check-added-large-files
    name: checking for added large files
    description: prevents giant files from being committed.
    entry: check-added-large-files
    language: python

  - id: check-merge-conflict
    name: checking merge conflicts
    description: checks for files that contain merge conflict strings.
    entry: check-merge-conflict
    language: python
    types: [text]

  - id: end-of-file-fixer
    name: fix end of files
    description: ensures that a file is either empty, or ends with one newline.
    entry: end-of-file-fixer
    language: python
    types: [text]
    stages: [pre-commit, pre-push, manual]

  - id: name-tests-test
    name: check-tests-name
    description: ensures that the tests files have the correct nomenclature.
    entry: name-tests-test --pytest-test-first
    language: system
    types: [python]

- repo: https://github.com/psf/black
  rev: 24.10.0
  hooks:
  - id: black
    name: black
    description: "Black: The uncompromising Python code formatter"
    entry: black
    language: python
    require_serial: true
    types_or: [python, pyi]

  - id: black-jupyter
    name: black-jupyter
    description: "Black: The uncompromising Python code formatter (with Jupyter Notebook support)"
    entry: black
    language: python
    require_serial: true
    types_or: [python, pyi, jupyter]
    additional_dependencies: [".[jupyter]"]

- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
  - id: isort
    name: isort
    entry: isort
    stages: [pre-commit, pre-merge-commit, pre-push, manual]
    require_serial: true
    language: python
    types_or: [cython, pyi, python]
    args: ['--filter-files']

- repo: https://github.com/jazzband/pip-tools
  rev: 7.4.0
  hooks:
  - id: pip-compile
    name: pip-compile
    description: Automatically compile requirements.
    entry: pip-compile
    language: python
    files: ^requirements\.(in|txt)$
    pass_filenames: false
